Repository construct/construct, pull requests merged in 2020-01, with the labels that each got.

#788 add testcase (marked as xfail) for issue #781
  tests/test_core.py
Labels: bug found

#760 allow Select to build from none if any of its subcons can
  construct/core.py
  tests/test_core.py
Labels: feature request

#749 Patch Optional() when restreamed issue
  construct/lib/bitstream.py
  tests/test_core.py
Labels: enhancement

#834 add python version requirement to setup.py
  setup.py
Labels: enhancement
